export default {
  LOGIN_FORM_CHANGED: 'LOGIN_FORM_CHANGED',
  LOGIN_FIELDS_ERRORS: 'LOGIN_FIELDS_ERRORS',
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  ON_AUTH_SUCCESS: 'ON_AUTH_SUCCESS',
}